export const DATE_FIELDS = ['start_date', 'end_date', 'reported_date', 'published_date']
export const AND_COLUMNS = [...DATE_FIELDS, 'number_affected']
export const COLUMNS = [
  'state',
  'entity_name',
  'dba',
  'business_address',
  'business_city',
  'business_state',
  'business_zip',
  'start_date',
  'end_date',
  'breach_dates',
  'reported_date',
  'number_affected',
  'data_accessed',
  'notice_methods',
  'published_date',
  'breach_type',
  'data_source', // HIPAA only
  'letter_url',
  'url',
]
export const COLUMN_DISPLAY_NAMES = {
  state: 'State',
  entity_name: 'Entity name',
  dba: 'd.b.a.',
  business_address: 'Biz address',
  business_city: 'Biz city',
  business_state: 'Biz state',
  business_zip: 'Biz ZIP',
  start_date: 'Start date',
  end_date: 'End date',
  breach_dates: 'Breach dates',
  reported_date: 'Reported date',
  number_affected: '#&nbsp;affected',
  data_accessed: 'Data accessed',
  notice_methods: 'Notices given',
  published_date: 'Publish date',
  breach_type: 'Type of breach',
  data_source: 'Data source',
  letter_url: 'Notification',
  url: 'URL',
}
export const COLUMN_DATA_DEFAULTS = {
  state: '??',
  entity_name: 'Unknown',
  dba: 'N/A',
  business_address: 'N/A',
  business_city: 'N/A',
  business_state: 'N/A',
  business_zip: 'N/A',
  start_date: '-',
  end_date: '-',
  breach_dates: '-',
  reported_date: '-',
  number_affected: '-',
  data_accessed: '-',
  notice_methods: '-',
  published_date: 'N/A',
  breach_type: '-',
  data_source: '-',
  letter_url: 'N/A',
  url: 'N/A',
}
export const COLS_BY_STATE = {
  CA: ['entity_name', 'breach_dates', 'reported_date'],
  DE: ['entity_name', 'start_date', 'end_date', 'breach_dates', 'reported_date', 'number_affected', 'breach_type', 'data_source'],
  HI: ['entity_name', 'reported_date', 'number_affected', 'breach_type', 'data_source', 'letter_url'],
  IA: ['entity_name', 'reported_date', 'breach_type', 'data_source', 'letter_url'],
  MD: ['entity_name', 'reported_date', 'number_affected', 'data_accessed', 'breach_type', 'data_source'],
  ME: ['entity_name', 'reported_date', 'breach_type', 'data_source', 'url'],
  MT: ['entity_name', 'letter_url', 'start_date', 'end_date', 'reported_date', 'number_affected', 'breach_type', 'data_source'],
  ND: ['entity_name', 'dba', 'letter_url', 'start_date', 'end_date', 'breach_dates', 'reported_date', 'number_affected', 'breach_type', 'data_source'],
  NH: ['entity_name', 'reported_date', 'breach_type', 'data_source', 'url'],
  NJ: ['entity_name', 'reported_date', 'breach_type', 'data_source', 'url'],
  OR: ['entity_name', 'start_date', 'end_date', 'breach_dates', 'reported_date', 'breach_type', 'data_source'],
  TX: [
    'entity_name', 'business_address', 'business_city', 'business_state', 'business_zip',
    'published_date', 'number_affected', 'data_accessed', 'breach_type', 'data_source', 'notice_methods'
  ],
  WA: ['entity_name', 'start_date', 'reported_date', 'number_affected', 'data_accessed', 'breach_type', 'data_source', 'letter_url'],
  WI: ['entity_name', 'breach_dates', 'reported_date', 'number_affected', 'data_accessed'],
  HIPAA: ['entity_name', 'state', 'reported_date', 'number_affected', 'breach_type', 'data_source'], 
}
